# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPSZmxW3srtKfa5QQ7yU1e-hSyDupbbq
"""

from google.colab import files
uploaded=files.upload()

from keras.models import load_model
import numpy as np

# Load the model
loaded_model = load_model('model_ids.hdf5')

from sklearn.preprocessing import Normalizer

trial=np.array([[0,1,34,13,66,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00]])
trial.astype(float)


scaler = Normalizer().fit(trial)
trial = scaler.transform(trial)

X_trial = np.array(trial)
X_trial

pred=loaded_model.predict(X_trial)

if(pred<0.5):
    pred=0
else:
    pred=1

print(pred)